// Fully populated character data - Review and adjust placeholders as needed!

export const characters = [
  {
    id: 'rylon_01',
    name: 'Captain Rylon',
    faction: 'Trade Consortium',
    origin: 'Sovereign Reach Trade Hub',
    portrait: '/assets/characters/CaptainRylon.png',
    modelPath: '/assets/models/Characters/Captain Rylon Idle.glb',
    scale: 1,
    shortBio: 'A seasoned captain known for reliable transport and sharp wits.',
    fullBio: 'Captain Rylon has seen their fair share of asteroid belts and shady deals. Starting with a salvaged freighter, they built a reputation for dependability, navigating both trade lanes and treacherous negotiations with equal skill. Rylon values loyalty and a fair contract above all else.',
    stats: {
      Piloting: 5.8,
      Tech: 4.0,
      Combat: 3.8,
      Influence: 5.5,
      Perception: 4.5,
    },
    specialAbilities: [
      { name: 'Cargo Optimization', description: 'Slightly increases cargo capacity.' },
      { name: 'Veteran Navigator', description: 'Reduces travel time occasionally.' },
    ],
    shipName: 'The Steady Hauler',
    shipClass: 'Medium Freighter',
  },
  {
    id: 'kira_01',
    name: 'Kira Sunsong',
    faction: 'Galactic Concordat',
    origin: 'Aetheria Sky-City',
    portrait: '/assets/characters/KiraSusong.png',
    modelPath: '/assets/models/Characters/KiraSusong Idle.glb',
    scale: 1,
    shortBio: 'An idealistic envoy seeking peaceful resolutions across the stars.',
    fullBio: 'Raised in the serene sky-cities of Aetheria, Kira believes in the power of dialogue and understanding. She travels the systems seeking to build bridges between disparate factions, often putting herself at risk for the sake of peace. Her empathy is her greatest strength and, sometimes, her weakness.',
    stats: {
      Piloting: 3.8,
      Tech: 3.5,
      Combat: 3.5,
      Influence: 6.0,
      Perception: 5.2,
    },
    specialAbilities: [
      { name: 'Cultural Empathy', description: 'Improves initial standing with new factions.' },
      { name: 'Ceasefire Accord', description: 'Can attempt to de-escalate certain hostile encounters.' },
    ],
    shipName: 'The Emissary Dove',
    shipClass: 'Courier Vessel',
  },
  {
    id: 'kamboja_01',
    name: 'Kamboja',
    faction: 'Explorer',
    origin: 'Riau Archipelago Diaspora',
    portrait: '/assets/characters/Kamboja.PNG',
    modelPath: '/assets/models/Characters/Kamboja Idle.glb',
    scale: 1,
    shortBio: 'Descendant of ancient sea kings, charting the modern stellar ocean.',
    fullBio: 'Hailing from a lineage tracing back to the Bugis navigators and Riau Lingga royalty of Old Earth, Kamboja carries the spirit of exploration in their blood. They seek not conquest, but understanding, mapping the furthest reaches and facing the unknown with quiet determination and ancestral wisdom adapted for the void.',
    stats: {
      Piloting: 5.9,
      Tech: 4.8,
      Combat: 4.0,
      Influence: 3.5,
      Perception: 5.8,
    },
    specialAbilities: [
      { name: 'Void Navigator', description: 'Reduced chance of getting lost or encountering navigational hazards.' },
      { name: 'Ancient Echoes', description: 'Occasionally intuits information about unexplored systems or ruins.' },
    ],
    shipName: 'The Sea Serpent',
    shipClass: 'Deep Space Pinnace',
  },
  {
    id: 'vex_01',
    name: 'Zara Vex',
    faction: 'Aegis Command',
    origin: 'Quantara Prime Orbital Command',
    portrait: '/assets/characters/ZaraVex.png',
    modelPath: '/assets/models/Characters/Zara Vex Idle.glb',
    scale: 1,
    shortBio: 'A disciplined strategist with unmatched tactical prowess.',
    fullBio: 'Zara Vex rose through the ranks of the Sovereign Reach fleet with distinction. Known for meticulous planning and decisive execution, Vex is a formidable presence on any bridge. Duty and order guide their every move, enforcing the Reach\'s dominance.',
    stats: {
      Piloting: 5.5,
      Tech: 4.2,
      Combat: 6.0,
      Influence: 3.9,
      Perception: 5.0,
    },
    specialAbilities: [
      { name: 'Fleet Commander', description: 'Improves effectiveness of allied ships in combat maneuvers.' },
      { name: 'Advanced Targeting Systems', description: 'Increases ship weapon accuracy and critical hit chance.' },
    ],
    shipName: 'The Aegis Hammer',
    shipClass: 'Heavy Cruiser',
  },
  {
    id: 'pax_01',
    name: 'Orion Pax',
    faction: "Prospector's Union",
    origin: "Frontier's Edge Mining Cooperative",
    portrait: '/assets/characters/OrionPax.PNG',
    modelPath: '/assets/models/Characters/Orion Pax Idle.glb',
    scale: 1,
    shortBio: 'A brilliant engineer fascinated by ancient alien technology.',
    fullBio: "Orion Pax spent years uncovering forgotten tech in abandoned mines and derelict ruins. Driven by a thirst for knowledge and a talent for reverse-engineering, Pax seeks to unlock the secrets of the past to build a better future, often venturing where others fear to tread.",
    stats: {
      Piloting: 3.6,
      Tech: 6.0,
      Combat: 3.5,
      Influence: 4.0,
      Perception: 5.9,
    },
    specialAbilities: [
      { name: 'Ancient Tech Expert', description: 'Can interface with or repair certain alien technologies.' },
      { name: 'Resourceful Scavenger', description: 'Improved chance to find rare components and salvage.' },
    ],
    shipName: "The Prospector's Dream",
    shipClass: 'Deep Space Explorer',
  },
  {
    id: 'niles_01',
    name: 'Governor Niles',
    faction: 'Core Directorate',
    origin: 'High Council Chambers, Aetheria',
    portrait: '/assets/characters/GovenorNiles.png',
    modelPath: '/assets/models/Characters/Governor Niles Idle.glb',
    scale: 1,
    shortBio: 'A cunning politician navigating the complex web of interstellar diplomacy.',
    fullBio: 'Governor Niles wields influence and bureaucracy like weapons. Adept at navigating political minefields and brokering deals, Niles seeks to expand the Consortium\'s power, using charm and veiled threats in equal measure. Alliances are temporary; power is eternal.',
    stats: {
      Piloting: 3.5,
      Tech: 3.5,
      Combat: 3.5,
      Influence: 5.9,
      Perception: 4.2,
    },
    specialAbilities: [
      { name: 'Bureaucratic Maze', description: 'Can delay or obstruct hostile actions through diplomatic channels.' },
      { name: 'Powerful Connections', description: 'Occasionally gains access to restricted information or high-level contacts.' },
    ],
    shipName: "The Diplomat's Insignia",
    shipClass: 'Luxury Yacht',
  },
];